v9.21: Fix build error - move isEncryptionActive() out of header
IConnection is only forward-declared in client.h, so calling
m_con->IsPeerEncryptionActive() inline in the header causes:
  error: invalid use of incomplete type 'class con::IConnection'

Move the implementation to client.cpp where IConnection is fully
defined via #include 'network/connection.h'.